### ISSUE TITLE
LKIF-Core Vocabularly implementation within Apache Any23 

### ISSUE THREAD

**Issue by lewismc** [RinkeHoekstra/lkif-core#1]
Hi Rinke,
I recently implemented [0] the entire LKIF-Core vocabulary within Apache Any23 [1] and thought I would bring it to your attention.
The rationale behind this is that the vocabularies make up the core ontologies used by Any23 when parsing and extracting.
If you have some questions please head over to user@any23.apache.org mailing list.
All the best
Lewis

[0] http://svn.apache.org/repos/asf/any23/trunk/api/src/main/java/org/apache/any23/vocab/
[1] http://any23.apache.org

**Comment by RinkeHoekstra** [comment]
Hi Lewis,

That's fantastic news! It would make sense to make LKIF Core a bit more Semantic Web/Linked Data enabled by hosting it properly (with content negotiation etc.). In the past I set up a purl.org redirect, and changed the namespaces, but this never really caught on.

Let me know what you think, or go ahead and do it yourself ;) Unfortunately I do not have a lot of time on my hands to maintain LKIF Core, and I'd be happy to give it to the community (even if that's only the two of us ;))

Cheers,
Rinke

**Comment by lewismc** [comment]
I certianly think purl is a good idea to abstract away from the underlying ontology. If you wish to pick an appropriate purl ns then I can get it sorted for sure.
Thanks
Lewis

**Comment by lewismc** [comment]
The joys of mobile browsing. I accidentally closed the issue after commenting several times!!!
Anyway. if you can suggest a reasonable NS then we can get it registered on purl and also begin to disseminate.
